// let d = [
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U15",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "California State Outdoor",
//     "Event - Location": "Simi Valley, CA",
//     "Event - Distance": "50m",
//     "Score - Score": 860,
//     "Score - Average": 5.972,
//     "Score - Placement": "2nd"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U15",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "USA Archery JOAD Target Nationals",
//     "Event - Location": "Decatur, AL",
//     "Event - Distance": "30m",
//     "Score - Score": 1166,
//     "Score - Average": 8.097,
//     "Score - Placement": "1st"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U15",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "Chia Archery Championship",
//     "Event - Location": "Sacramento, CA",
//     "Event - Distance": "18m",
//     "Score - Score": 437,
//     "Score - Average": 7.283,
//     "Score - Placement": "4th"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U18",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "World Archery Championships and Pan Am Games U.S. Team Trials",
//     "Event - Location": "Phoenix, AZ",
//     "Event - Distance": "50m",
//     "Score - Score": 370,
//     "Score - Average": 5.139,
//     "Score - Placement": "4th"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U18",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "USA Archery JOAD Target Nationals",
//     "Event - Location": "Des Moines, IA",
//     "Event - Distance": "50m",
//     "Score - Score": 966,
//     "Score - Average": 6.708,
//     "Score - Placement": "3rd"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U15",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "California State Outdoor",
//     "Event - Location": "Tulare, CA",
//     "Event - Distance": "30m",
//     "Score - Score": 390,
//     "Score - Average": 5.417,
//     "Score - Placement": "1st"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U15",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "California State Indoor",
//     "Event - Location": "Tulare, CA",
//     "Event - Distance": "18m",
//     "Score - Score": 625,
//     "Score - Average": 5.208,
//     "Score - Placement": "3rd"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U15",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "Pacific Coast Championship",
//     "Event - Location": "Simi Valley, CA",
//     "Event - Distance": "30m",
//     "Score - Score": 389,
//     "Score - Average": 5.403,
//     "Score - Placement": "1st"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U18",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "Pacific Coast Championship",
//     "Event - Location": "Sacramento, CA",
//     "Event - Distance": "50m",
//     "Score - Score": 643,
//     "Score - Average": 4.465,
//     "Score - Placement": "2nd"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U18",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "Grapestakes",
//     "Event - Location": "Sacramento, CA",
//     "Event - Distance": "50m",
//     "Score - Score": 846,
//     "Score - Average": 5.875,
//     "Score - Placement": "1st"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U15",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "USA Archery Indoor Nationals Final",
//     "Event - Location": "Louisville, KY",
//     "Event - Distance": "18m",
//     "Score - Score": 679,
//     "Score - Average": 5.658,
//     "Score - Placement": "N/A"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U15",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "Grapestakes",
//     "Event - Location": "Sacramento, CA",
//     "Event - Distance": "50m",
//     "Score - Score": 635,
//     "Score - Average": 4.41,
//     "Score - Placement": "1st"
//   },
//   {
//     "Person - Name First": "Felix",
//     "Person - Name Last": "Waterman",
//     "Person - Division": "U18",
//     "Person - Discipline": "Barebow",
//     "Event - Name": "SoCal Showdown",
//     "Event - Location": "San Diego, CA",
//     "Event - Distance": "50m",
//     "Score - Score": 356,
//     "Score - Average": 4.944,
//     "Score - Placement": "5th"
//   }
// ]